const { Pool } = require('pg');
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false, max: 20, idleTimeoutMillis: 30000 });
pool.on('error', (err) => console.error('Pool error:', err.message));
async function initDB() {
  const client = await pool.connect();
  try { await client.query('SELECT NOW()'); console.log('OK Database connected'); await migrate(client); console.log('OK Migrations complete'); }
  finally { client.release(); }
}
async function migrate(client) {
  await client.query('CREATE TABLE IF NOT EXISTS organizations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, plan TEXT DEFAULT \'starter\', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())');
  await client.query('CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, name TEXT NOT NULL, role TEXT DEFAULT \'member\', avatar_url TEXT, last_login TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW())');
  await client.query('CREATE TABLE IF NOT EXISTS agents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, name TEXT NOT NULL DEFAULT \'ARIA\', is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())');
  await client.query('CREATE TABLE IF NOT EXISTS contacts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, name TEXT, phone TEXT NOT NULL, email TEXT, company TEXT, source TEXT DEFAULT \'inbound_call\', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())');
  await client.query('CREATE TABLE IF NOT EXISTS calls (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, agent_id UUID REFERENCES agents(id), contact_id UUID REFERENCES contacts(id), twilio_call_sid TEXT UNIQUE, caller_phone TEXT NOT NULL, caller_name TEXT, direction TEXT DEFAULT \'inbound\', call_type TEXT DEFAULT \'general\', outcome TEXT DEFAULT \'answered\', duration_seconds INTEGER DEFAULT 0, summary TEXT, transcript TEXT, sentiment TEXT, intent_scores JSONB DEFAULT \'{}\', extracted_data JSONB DEFAULT \'{}\', recording_url TEXT, crm_synced BOOLEAN DEFAULT false, crm_contact_id TEXT, started_at TIMESTAMPTZ DEFAULT NOW(), ended_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW())');
  await client.query('CREATE TABLE IF NOT EXISTS recordings (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), call_id UUID REFERENCES calls(id) ON DELETE CASCADE, org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, twilio_recording_sid TEXT, url TEXT, duration_seconds INTEGER, transcript TEXT, created_at TIMESTAMPTZ DEFAULT NOW())');
  await client.query('CREATE TABLE IF NOT EXISTS appointments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, contact_id UUID REFERENCES contacts(id), call_id UUID REFERENCES calls(id), title TEXT, contact_name TEXT NOT NULL, contact_phone TEXT NOT NULL, contact_email TEXT, service_type TEXT, scheduled_at TIMESTAMPTZ NOT NULL, duration_minutes INTEGER DEFAULT 60, status TEXT DEFAULT \'confirmed\', booked_via TEXT DEFAULT \'voice\', notes TEXT, reminder_sent BOOLEAN DEFAULT false, crm_event_id TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())');
  await client.query('CREATE TABLE IF NOT EXISTS voicemails (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, contact_id UUID REFERENCES contacts(id), call_id UUID REFERENCES calls(id), caller_name TEXT, caller_phone TEXT NOT NULL, recording_url TEXT, transcript TEXT, duration_seconds INTEGER DEFAULT 0, is_read BOOLEAN DEFAULT false, sms_recovery_sent BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT NOW())');
  await client.query('CREATE TABLE IF NOT EXISTS faqs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, agent_id UUID REFERENCES agents(id), question TEXT NOT NULL, answer TEXT NOT NULL, category TEXT DEFAULT \'general\', usage_count INTEGER DEFAULT 0, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW())');
  await client.query('CREATE TABLE IF NOT EXISTS conversations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, contact_id UUID REFERENCES contacts(id), channel TEXT DEFAULT \'sms\', status TEXT DEFAULT \'open\', last_message TEXT, last_message_at TIMESTAMPTZ, unread_count INTEGER DEFAULT 0, assigned_to UUID REFERENCES users(id), created_at TIMESTAMPTZ DEFAULT NOW())');
  await client.query('CREATE TABLE IF NOT EXISTS messages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), conversation_id UUID REFERENCES conversations(id) ON DELETE CASCADE, org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, direction TEXT DEFAULT \'outbound\', channel TEXT DEFAULT \'sms\', body TEXT NOT NULL, status TEXT DEFAULT \'sent\', sender_name TEXT, created_at TIMESTAMPTZ DEFAULT NOW())');
  await client.query('CREATE TABLE IF NOT EXISTS notifications (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, user_id UUID REFERENCES users(id), type TEXT NOT NULL, title TEXT NOT NULL, body TEXT, icon TEXT DEFAULT \'bell\', color TEXT DEFAULT \'gray\', reference_id UUID, reference_type TEXT, is_read BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT NOW())');
  await client.query('CREATE TABLE IF NOT EXISTS integrations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, provider TEXT NOT NULL, config JSONB DEFAULT \'{}\', is_active BOOLEAN DEFAULT false, last_sync TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(org_id, provider))');
  await client.query('CREATE TABLE IF NOT EXISTS events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, event_type TEXT NOT NULL, payload JSONB DEFAULT \'{}\', processed BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT NOW())');
  const a = async (t,c,tp) => { try { await client.query('ALTER TABLE '+t+' ADD COLUMN IF NOT EXISTS '+c+' '+tp); } catch(e) {} };
  await a('organizations','twilio_account_sid','TEXT'); await a('organizations','twilio_auth_token','TEXT'); await a('organizations','twilio_phone_number','TEXT'); await a('organizations','openai_api_key','TEXT'); await a('organizations','elevenlabs_api_key','TEXT'); await a('organizations','elevenlabs_voice_id','TEXT'); await a('organizations','deepgram_api_key','TEXT'); await a('organizations','ghl_api_key','TEXT'); await a('organizations','ghl_location_id','TEXT'); await a('organizations','hubspot_api_key','TEXT'); await a('organizations','notification_email','TEXT'); await a('organizations','notification_sms','TEXT'); await a('organizations','slack_webhook_url','TEXT'); await a('organizations','sendgrid_api_key','TEXT'); await a('organizations','google_calendar_id','TEXT'); await a('organizations','calendly_api_key','TEXT'); await a('organizations','timezone','TEXT'); await a('organizations','features','JSONB'); await a('organizations','white_label_domain','TEXT');
  await a('agents','industry','TEXT'); await a('agents','voice_provider','TEXT'); await a('agents','voice_id','TEXT'); await a('agents','voice_name','TEXT'); await a('agents','voice_settings','JSONB'); await a('agents','system_prompt','TEXT'); await a('agents','greeting','TEXT'); await a('agents','after_hours_msg','TEXT'); await a('agents','goodbye_msg','TEXT'); await a('agents','transfer_number','TEXT'); await a('agents','transfer_prompt','TEXT'); await a('agents','escalation_keywords','TEXT[]'); await a('agents','booking_enabled','BOOLEAN'); await a('agents','booking_prompt','TEXT'); await a('agents','faq_enabled','BOOLEAN'); await a('agents','voicemail_enabled','BOOLEAN'); await a('agents','sms_followup_enabled','BOOLEAN'); await a('agents','sms_followup_template','TEXT'); await a('agents','max_call_duration','INTEGER'); await a('agents','silence_timeout','INTEGER'); await a('agents','workflow','JSONB');
  await a('contacts','address','TEXT'); await a('contacts','city','TEXT'); await a('contacts','state','TEXT'); await a('contacts','zip','TEXT'); await a('contacts','tags','TEXT[]'); await a('contacts','lead_score','INTEGER'); await a('contacts','status','TEXT'); await a('contacts','pipeline_stage','TEXT'); await a('contacts','crm_contact_id','TEXT'); await a('contacts','crm_synced','BOOLEAN'); await a('contacts','last_contact_at','TIMESTAMPTZ'); await a('contacts','notes','TEXT'); await a('contacts','custom_fields','JSONB');
  try { await client.query('CREATE INDEX IF NOT EXISTS idx_calls_org ON calls(org_id,started_at DESC)'); } catch(e) {}
  try { await client.query('CREATE INDEX IF NOT EXISTS idx_contacts_phone ON contacts(org_id,phone)'); } catch(e) {}
}
module.exports = { pool, initDB };
