const { Pool } = require('pg');
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false,
  max: 20, idleTimeoutMillis: 30000,
});
pool.on('error', (err) => console.error('Pool error:', err.message));
async function initDB() {
  const client = await pool.connect();
  try {
    await client.query('SELECT NOW()');
    console.log('OK Database connected');
    await migrate(client);
    console.log('OK Migrations complete');
  } finally { client.release(); }
}
async function migrate(client) {
  await client.query(`
    CREATE TABLE IF NOT EXISTS organizations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, plan TEXT DEFAULT 'starter', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, name TEXT NOT NULL, role TEXT DEFAULT 'member', avatar_url TEXT, last_login TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS agents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, name TEXT NOT NULL DEFAULT 'ARIA', is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS contacts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, name TEXT, phone TEXT NOT NULL, email TEXT, company TEXT, source TEXT DEFAULT 'inbound_call', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS calls (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, agent_id UUID REFERENCES agents(id), contact_id UUID REFERENCES contacts(id), twilio_call_sid TEXT UNIQUE, caller_phone TEXT NOT NULL, caller_name TEXT, direction TEXT DEFAULT 'inbound', call_type TEXT DEFAULT 'general', outcome TEXT DEFAULT 'answered', duration_seconds INTEGER DEFAULT 0, summary TEXT, transcript TEXT, sentiment TEXT, intent_scores JSONB DEFAULT '{}', extracted_data JSONB DEFAULT '{}', recording_url TEXT, crm_synced BOOLEAN DEFAULT false, crm_contact_id TEXT, started_at TIMESTAMPTZ DEFAULT NOW(), ended_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS recordings (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), call_id UUID REFERENCES calls(id) ON DELETE CASCADE, org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, twilio_recording_sid TEXT, url TEXT, duration_seconds INTEGER, transcript TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS appointments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, contact_id UUID REFERENCES contacts(id), call_id UUID REFERENCES calls(id), title TEXT, contact_name TEXT NOT NULL, contact_phone TEXT NOT NULL, contact_email TEXT, service_type TEXT, scheduled_at TIMESTAMPTZ NOT NULL, duration_minutes INTEGER DEFAULT 60, status TEXT DEFAULT 'confirmed', booked_via TEXT DEFAULT 'voice', notes TEXT, reminder_sent BOOLEAN DEFAULT false, crm_event_id TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS voicemails (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, contact_id UUID REFERENCES contacts(id), call_id UUID REFERENCES calls(id), caller_name TEXT, caller_phone TEXT NOT NULL, recording_url TEXT, transcript TEXT, duration_seconds INTEGER DEFAULT 0, is_read BOOLEAN DEFAULT false, sms_recovery_sent BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS faqs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, agent_id UUID REFERENCES agents(id), question TEXT NOT NULL, answer TEXT NOT NULL, category TEXT DEFAULT 'general', usage_count INTEGER DEFAULT 0, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS conversations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, contact_id UUID REFERENCES contacts(id), channel TEXT DEFAULT 'sms', status TEXT DEFAULT 'open', last_message TEXT, last_message_at TIMESTAMPTZ, unread_count INTEGER DEFAULT 0, assigned_to UUID REFERENCES users(id), created_at TIMESTAMPTZ DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS messages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), conversation_id UUID REFERENCES conversations(id) ON DELETE CASCADE, org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, direction TEXT DEFAULT 'outbound', channel TEXT DEFAULT 'sms', body TEXT NOT NULL, status TEXT DEFAULT 'sent', sender_name TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS notifications (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, user_id UUID REFERENCES users(id), type TEXT NOT NULL, title TEXT NOT NULL, body TEXT, icon TEXT DEFAULT 'bell', color TEXT DEFAULT 'gray', reference_id UUID, reference_type TEXT, is_read BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS integrations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, provider TEXT NOT NULL, config JSONB DEFAULT '{}', is_active BOOLEAN DEFAULT false, last_sync TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(org_id, provider));
    CREATE TABLE IF NOT EXISTS events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), org_id UUID REFERENCES organizations(id) ON DELETE CASCADE, event_type TEXT NOT NULL, payload JSONB DEFAULT '{}', processed BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT NOW());
  `);
  const a = (t,c,tp) => client.query("ALTER TABLE "+t+" ADD COLUMN IF NOT EXISTS "+c+" "+tp).catch(()=>{});
  for(const[c,t]of[["twilio_account_sid","TEXT"],["twilio_auth_token","TEXT"],["twilio_phone_number","TEXT"],["openai_api_key","TEXT"],["elevenlabs_api_key","TEXT"],["elevenlabs_voice_id","TEXT DEFAULT 'EXAVITQu4vr4xnSDxMaL'"],["deepgram_api_key","TEXT"],["ghl_api_key","TEXT"],["ghl_location_id","TEXT"],["hubspot_api_key","TEXT"],["notification_email","TEXT"],["notification_sms","TEXT"],["slack_webhook_url","TEXT"],["sendgrid_api_key","TEXT"],["google_calendar_id","TEXT"],["calendly_api_key","TEXT"],["timezone","TEXT DEFAULT 'America/Chicago'"],["business_hours","JSONB DEFAULT '{}'"],["features","JSONB DEFAULT '{}'"],["white_label_domain","TEXT"]]){await a("organizations",c,t);}
  for(const[c,t]of[["industry","TEXT DEFAULT 'general'"],["voice_provider","TEXT DEFAULT 'elevenlabs'"],["voice_id","TEXT DEFAULT 'EXAVITQu4vr4xnSDxMaL'"],["voice_name","TEXT DEFAULT 'Rachel'"],["voice_settings","JSONB DEFAULT '{"stability":0.75}'"],["system_prompt","TEXT DEFAULT 'You are a professional AI receptionist.'"],["greeting","TEXT DEFAULT 'Thank you for calling! How can I help?'"],["after_hours_msg","TEXT DEFAULT 'We are closed. Please leave a message.'"],["goodbye_msg","TEXT DEFAULT 'Thank you for calling. Have a great day!'"],["transfer_number","TEXT"],["transfer_prompt","TEXT DEFAULT 'Let me connect you with a team member.'"],["escalation_keywords","TEXT[] DEFAULT ARRAY['emergency','urgent']"],["booking_enabled","BOOLEAN DEFAULT true"],["booking_prompt","TEXT DEFAULT 'I can schedule an appointment.'"],["faq_enabled","BOOLEAN DEFAULT true"],["voicemail_enabled","BOOLEAN DEFAULT true"],["sms_followup_enabled","BOOLEAN DEFAULT true"],["sms_followup_template","TEXT DEFAULT 'We missed your call!'"],["max_call_duration","INTEGER DEFAULT 600"],["silence_timeout","INTEGER DEFAULT 5"],["workflow","JSONB DEFAULT '[]'"]]){await a("agents",c,t);}
  for(const[c,t]of[["address","TEXT"],["city","TEXT"],["state","TEXT"],["zip","TEXT"],["tags","TEXT[] DEFAULT '{}'"],["lead_score","INTEGER DEFAULT 0"],["status","TEXT DEFAULT 'new'"],["pipeline_stage","TEXT DEFAULT 'new'"],["crm_contact_id","TEXT"],["crm_synced","BOOLEAN DEFAULT false"],["last_contact_at","TIMESTAMPTZ"],["notes","TEXT"],["custom_fields","JSONB DEFAULT '{}'"]]){await a("contacts",c,t);}
  await client.query("CREATE INDEX IF NOT EXISTS idx_calls_org ON calls(org_id,started_at DESC);CREATE INDEX IF NOT EXISTS idx_contacts_org_phone ON contacts(org_id,phone);");
}
module.exports = { pool, initDB };
